### ISSUE TITLE
Registration Form Fields

### ISSUE THREAD

**Issue by MOkada0926** [tacsotai/flutter_bluesky#107]
Hard to know what to register

This screen asked for a user name, but it was unclear.

**Comment by tacsotai** [comment]
I see, the account name is required by bluesky spec.
All we can do is changing the messege "ユーザー登録フォームを全て入力してください"
Which messege is good for you ?

**Comment by tacsotai** [comment]
文言修正で良い。

**Comment by MOkada0926** [comment]
以下のように文言を変えていただくと、
パッと見でユーザーに何を入力してほしいのか伝わると思います。

①「ユーザー登録フォームを全て入力してください」
→「使用するユーザー名を入力してください」

②「アカウント」
→「ユーザー名」

③「ユーザー登録」
→「登録」
