### ISSUE TITLE
Save login status

### ISSUE THREAD

**Issue by MOkada0926** [tacsotai/flutter_bluesky#109]
I want to save my login status.

Now I have to log in every time I start my browser

**Comment by tacsotai** [comment]
It occuerd local env with the command: flutter run -d chrome
```
Error: Expected a value of type 'List<dynamic>', but got one of type 'Null'
stacktrace: dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 121:3       castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 529:12  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 638:14     as_C
packages/flutter_bluesky/api/model/feed.dart 12:14                                new
packages/flutter_bluesky/screen/data/manager.dart 39:32                           getData
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54
```

**Comment by tacsotai** [comment]
Check session for all pages.
```
Widget build(BuildContext context) 
```
for 
>      routes: {
~~>    　 Provider.screen.route: (context) => const Provider(),~~
~~>         LoginScreen.route: (context) => const LoginScreen(),~~
>         Base.route: (context) => Base(),
>         Post.screen.route: (context) => const Post(),
>         Thread.screen.route: (context) => const Thread(),
>         Profile.screen.route: (context) => const Profile(),
>         EditProfile.screen.route: (context) => const EditProfile(),
>       },

**Comment by tacsotai** [comment]
Done the bug fix, wating for user test.

**Comment by tacsotai** [comment]
テストお願いします。

**Comment by MOkada0926** [comment]
確認できました。ブラウザを開き直しても、ログイン状態を維持できています。
