### ISSUE TITLE
ユーザー作成コンテンツに関する機能要件

### ISSUE THREAD

**Issue by t-ishibashi9** [tacsotai/flutter_bluesky#141]
Androidの場合、以下の機能を満たす必要があります。iOSも同様の機能要件があり、実装していないと審査を通らない可能性があります。
- 不適切なコンテンツをブロックする機能
- ユーザーをブロックする機能
- 不適切なコンテンツを通報する機能
- ユーザーを通報する機能
[Androidの参考資料](https://android-developers-jp.googleblog.com/2022/08/google-play-policy-webinar-august-2022-summary.html?m=1)

**Comment by tacsotai** [comment]
ありがとうごとざいます。API自体は用意されているのでWeb上でテストがある程度済んだら組んでいきます。

**Comment by tacsotai** [comment]
実装サンプル
コピーテキスト: 8be338c
ブロック: 5bf9f7a

**Comment by tacsotai** [comment]
現状のBlueSkyの実装状況を鑑みて以下を実装する。
- Report Account
~~- Block Account（実装ずみ）~~
- Report Post
- Delete Post（ついでに）
- Mute Account（ついでに）

**Comment by tacsotai** [comment]
## Report
HTTP POST: /xrpc/com.atproto.moderation.createReport
### Post
```
{
    "reasonType": "com.atproto.moderation.defs#reasonSpam",
    "subject": {
        "$type": "com.atproto.repo.strongRef",
        "uri": "at://did:plc:gbmextlcsanvvyg3pdcmiali/app.bsky.feed.post/3kbwifkqask2t",
        "cid": "bafyreicxjaejm2h57s3yffqdv6dys2p4ysw62yuh24kj4fejo5km6uwxna"
    }
}
```
### Account 
```
{
    "reasonType": "com.atproto.moderation.defs#reasonSpam",
    "subject": {
        "$type": "com.atproto.admin.defs#repoRef",
        "did": "did:plc:gbmextlcsanvvyg3pdcmiali"
    }
}
```
### Table: moderation_report
|id|subjectType|subjectDid|subjectUri|subjectCid|reasonType|reason|reportedByDid|createdAt|
|---:|:---|:---|:---|:---|:---|:---|:---|:---|
|1|com.atproto.repo.strongRef|did:plc:gbmextlcsanvvyg3pdcmiali|at://did:plc:gbmextlcsanvvyg3pdcmiali/app.bsky.feed.post/3kbwifkqask2t|bafyreicxjaejm2h57s3yffqdv6dys2p4ysw62yuh24kj4fejo5km6uwxna|com.atproto.moderation.defs#reasonSpam|NULL|did:plc:i3xcvy2v755srqlghcz6quu5|2023-10-17T06:29:25.503Z|
|2|com.atproto.admin.defs#repoRef|did:plc:gbmextlcsanvvyg3pdcmiali|NULL|NULL|com.atproto.moderation.defs#reasonSpam|NULL|did:plc:i3xcvy2v755srqlghcz6quu5|2023-10-17T06:51:40.555Z|

**Comment by tacsotai** [comment]
Reportはテーブル上記録されるだけだけど、BlockはBlockされているということが分かるようにUIを少し変更する必要がある。

**Comment by tacsotai** [comment]
「不適切なコンテンツをブロックする機能」
は、ユーザーをブロックすることで実現される。

**Comment by tacsotai** [comment]
## ReasonType
理由種別はPostもAccountも同じ。ただし、Postのうち３つがAccountの時に指定される。
これを選べるようなUIを作る必要がある。

### [Report Post](https://github.com/bluesky-social/atproto/blob/44ea5e80fa6f8a8724ff29a06f7fa8fc5d7f57ef/packages/api/src/client/types/com/atproto/moderation/defs.ts#L10)
```
      "reasonType": {
        "type": "string",
        "knownValues": [
          "com.atproto.moderation.defs#reasonSpam",
          "com.atproto.moderation.defs#reasonViolation",
          "com.atproto.moderation.defs#reasonMisleading",
          "com.atproto.moderation.defs#reasonSexual",
          "com.atproto.moderation.defs#reasonRude",
          "com.atproto.moderation.defs#reasonOther"
        ]
      },
```
### [Report User](https://github.com/bluesky-social/social-app/blob/8e9cf182c2e247203b6b5ea9ae701c039945d6a0/src/view/com/modals/report/ReasonOptions.tsx#L49)
```
const AccountReportReasons = {
  [ComAtprotoModerationDefs.REASONMISLEADING]: {
    title: 'Misleading Account',
    description: 'Impersonation or false claims about identity or affiliation',
  },
  [ComAtprotoModerationDefs.REASONSPAM]: {
    title: 'Frequently Posts Unwanted Content',
    description: 'Spam; excessive mentions or replies',
  },
  [ComAtprotoModerationDefs.REASONVIOLATION]: {
    title: 'Name or Description Violates Community Standards',
    description: 'Terms used violate community standards',
  },
}
```

**Comment by tacsotai** [comment]
# [graph](https://github.com/bluesky-social/atproto/tree/44ea5e80fa6f8a8724ff29a06f7fa8fc5d7f57ef/lexicons/app/bsky/graph)

_Italic_ are defeind at flutter_bluesky.dart as wrapper of atproto.dart

## Follow
### def
app.bsky.graph.follow

### API
_app.bsky.graph.getFollowers_
_app.bsky.graph.getFollows_
com.atproto.repo.createRecord
com.atproto.repo.deleteRecord

## Block
### def
app.bsky.graph.block

### API
_app.bsky.graph.getBlocks_
com.atproto.repo.createRecord
com.atproto.repo.deleteRecord

## Mute

### Mute List API
app.bsky.graph.muteActorList
app.bsky.graph.unmuteActorList
_app.bsky.graph.getListMutes_

### Mute Actor API
app.bsky.graph.muteActor
app.bsky.graph.unmuteActor
_app.bsky.graph.getMutes_

## List

### def
app.bsky.graph.list
app.bsky.graph.listitem

### API
_app.bsky.graph.getLists_
app.bsky.graph.getList
com.atproto.repo.createRecord
com.atproto.repo.deleteRecord

**Comment by tacsotai** [comment]
The UI will be created at #159.
