### ISSUE TITLE
Fix scroll error

### ISSUE THREAD

**Issue by tacsotai** [tacsotai/flutter_bluesky#90]
The scroll view on Search and Notification are collapsed.
So, fix it.

**Comment by tacsotai** [comment]
The data sise is the cause. It is not happend at large size data.
So, consider to cut off the scroll function at small data.

**Comment by tacsotai** [comment]
It is difficult to fix by current coding skill of mine.
So, fix it in the future.

**Comment by erimaruyama** [comment]
Containers were flashed when user swiped from under to upside in this page![image](https://github.com/tacsotai/flutter_bluesky/assets/120287029/c8636a74-7450-403b-a191-805e00e2afde)

**Comment by erimaruyama** [comment]
A blank space was occurred ![image](https://github.com/tacsotai/flutter_bluesky/assets/120287029/219d2e3b-b7c3-461a-90d1-7069f8e57b8c)when user scroll from upside to downside.

**Comment by erimaruyama** [comment]
I can't get to the home screen without refreshing.
It takes a long time when the line is busy.

**Comment by tacsotai** [comment]
Thank you for your report.
I will handle it from 10/1 2023. It is complecated.

**Comment by tacsotai** [comment]
In the future we will fix at #120.
https://github.com/tacsotai/flutter_bluesky/issues/90#issuecomment-1654662019

**Comment by tacsotai** [comment]
Hint for getting size of render object.
https://qiita.com/kemmowner/items/4ef1af413de9f951f25d
